# Diskominfo Jabar Asset network Hyperledger Fabric
# diskominfo asset ledger blockhain network
# Author: PJ
#
# ---------------------------------------------------------------------------
# "OrdererOrgs" -define ordering node and Create an organization definition
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs for complete description
    # SANS: (Optional) Specifies one or more Subject Alternative Names
    # to be set in the resulting x509.
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
